include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

flatpak:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
    extends: '.flatpak'
    variables:
        MANIFEST_PATH: "flatpak/org.gnome.FileRoller.json"
        FLATPAK_MODULE: "file-roller"
        APP_ID: "org.gnome.FileRoller"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        BUNDLE: "file-roller-dev.flatpak"

nightly:
  extends: '.publish_nightly'
  dependencies: ['flatpak']
  needs: ['flatpak']
